#!/usr/bin/env python3
"""Render docs/for-agents/TABLES.md from data/schema/*.json. `--check` fails if the file is stale.

tests/test_hm_docs.py runs --check so docs and schema cannot drift apart.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from heavymap.schema import Schema  # noqa: E402

OUT = ROOT / "docs" / "for-agents" / "TABLES.md"


def render(schema):
    lines = ["# Tables (generated)", "",
             "<!-- Generated by scripts/gen_table_docs.py from data/schema/table-schema.json. Do not edit; run the script. -->", "",
             f"Schema version `{schema.version}`. Headers are ordered; `hm validate` rejects any other order. "
             "**Editable** = fields a review decision may change (`hm apply` whitelist). Empty = changed only by a reviewed PR.", ""]
    for stage in ("registry", "inbox", "runs", "reviewed"):
        group = [t for t in schema.tables.values() if t.stage == stage]
        if not group:
            continue
        lines += [f"## {stage}", ""]
        for t in group:
            lines += [f"### `{t.name}`", "", f"File: `{t.path}` - key: `{t.key}`", "", t.description, "",
                      "| Column | Editable | Required | Constraint |", "|---|---|---|---|"]
            for col in t.columns:
                cons = []
                if col in t.enums:
                    cons.append(f"one of `{t.enums[col]}` in controlled-values.json")
                if col in t.patterns:
                    cons.append(f"pattern `{t.patterns[col]}`")
                if col in t.fk:
                    cons.append(f"FK -> `{t.fk[col]}`")
                if col in t.dates:
                    cons.append("ISO date")
                if col in t.urls:
                    cons.append("http(s) URL(s), ` | ` separated")
                if col in t.ints:
                    cons.append("integer")
                lines.append(f"| `{col}` | {'yes' if col in t.editable else ''} | {'yes' if col in t.required else ''} | {'; '.join(cons).replace('|', chr(92) + '|')} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


if __name__ == "__main__":
    text = render(Schema(ROOT))
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
